//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powerplant
    {
        public int Id { get; set; }
        public Nullable<int> No_RPC { get; set; }
        public Nullable<decimal> Power { get; set; }
        public Nullable<decimal> PowerAvgYear { get; set; }
        public System.DateTime Launch { get; set; }
        public int PostalCode { get; set; }
        public string Streetname { get; set; }
        public string Streetnumber { get; set; }
        public decimal GPS_X { get; set; }
        public decimal GPS_Y { get; set; }
        public int PowerTypeId { get; set; }
        public string City { get; set; }
    
        public virtual PowerType PowerType { get; set; }
    }
}
